# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  - push
  - pull_request

jobs:
  test:
    environment: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8"]

    steps:
        shell: bash
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo $RANDOM_VAR
          echo ${{ secrets.RANDOM_VAR }}
          echo ${{ RANDOM_VAR }}
          python -m pip install --upgrade pip
          python -m pip install pytest
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          RANDOM_VAR: ${{ secrets.RANDOM_VAR }}
        run: |
          pytest